name: Test
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install
        run: |
          pnpm i npx -g
          pnpm install --frozen-lockfile

      - name: Lint
        shell: bash
        run: |
          pnpm run audit
          pnpm run lint

      - name: Build
        shell: bash
        run: |
          pnpm run build

      - name: Mocha tests
        shell: bash
        run: |
          pnpm run test:mocha:ci
